# Generated by Django 5.1.7 on 2025-04-06 17:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Nama hanya boleh mengandung nama, angka, dan strip '-'", regex='^[a-zA-Z0-9\\s\\-]+$')])),
                ('plant_type', models.CharField(max_length=50)),
                ('harvest_time', models.IntegerField(help_text='Harvest time in days')),
                ('description', models.TextField()),
                ('seed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in hectares', max_digits=10)),
                ('address', models.TextField(validators=[django.core.validators.RegexValidator(message="Address hanya dapat berisi huruf, angka, spasi, koma, titik, dan strip '-'", regex='^[a-zA-Z0-9\\s,.\\-]+$')])),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField()),
                ('estimated_harvest', models.DateField()),
                ('seed_count', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Preparation', 'Preparation'), ('Planting', 'Planting'), ('Maintenance', 'Maintenance'), ('Harvest', 'Harvest'), ('Failed', 'Failed')], default='Preparation', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='pertanian.field')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='pertanian.plant')),
            ],
        ),
    ]
