# Generated by Django 5.1.7 on 2025-03-17 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Masukkan format email yang valid.')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nama',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Nama hanya boleh diisi oleh huruf, angka, dan karakter titik (.), underscore (_), atau strip (-)', regex='^[a-zA-Z0-9._\\- ]+$')]),
        ),
    ]
