# Generated by Django 5.1.7 on 2025-03-18 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_username_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nama',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Nama hanya boleh diisi oleh huruf, angka, dan karakter titik (.), underscore (_), atau strip (-)', regex='^[a-zA-Z0-9._\\-]+$')]),
        ),
    ]
