# Generated by Django 5.1.7 on 2025-03-21 16:07

from django.db import migrations
from django.contrib.auth.hashers import make_password
from datetime import date

def create_default_admin(apps, schema_editor):
    CustomUser = apps.get_model('user', 'CustomUser')
    
    admin_data = {
        'nama': 'PKPLAdmin',
        'email': 'admin@pkpl.com',
        'password': make_password('PKPLAdmin123'),
        'tanggal_lahir': date(2000, 1, 1),  
        'nomor_hp': '6281234567890',     
        'url_blog': 'https://admin.example.com',
        'deskripsi_diri': 'Admin default sistem PKPL',
        'npwp': '12.345.678.9-012.345',   
        'status_sertifikasi': 'Belum',
        'is_staff': True,
        'is_superuser': True,
        'is_active': True
    }
    
    if not CustomUser.objects.filter(email=admin_data['email']).exists():
        CustomUser.objects.create(**admin_data)

class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),  # Sesuaikan dengan migration sebelumnya
    ]

    operations = [
        migrations.RunPython(create_default_admin),
    ]