# Generated by Django 5.1.7 on 2025-03-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_managers'),
        ('user', '0006_create_default_admin'),
    ]

    operations = [
    ]
